src/components/IconDetail.vue, src/window.d.ts
Fixes icon download in vscode environment
=> fix: icon downloads

src/components/IconDetail.vue, src/utils/bufferToSring.ts, src/utils/pack.ts
Fixes icon bag zip download in vscode environment
=> fix: icon zip download

src/components/ActionsMenu.vue, src/components/IconSet.vue, src/components/Navbar.vue
This pr improves dropdowns dark mode on Windows. I don't know how this changes effect on MacOS.
**With this pr:**
=> chore: improve dark mode

index.html, public/search.xml, src/components/IconSet.vue
This PR allow user directly search icon using address bar of browser.
=> feat: search using address bar

src/components/Drawer.vue
Hi, I think nav header set sticky is better.
=> feat(nav-header): set sticky

src/components/IconSet.vue, src/components/Navbar.vue
Hello 👋 
This PR addresses the #34 issue, by allowing Firefox users to right-click on the search input to "Add A Keyword for this Search...".
=> feat: Firefox Smart Keywords implementation, closes #34

src/components/IconDetail.vue, src/utils/icons.ts
=> feat: add unplugin icon snippets

vite.config.ts
Cache assets in the `/public` folder.
=> Better service worker

src/utils/icons.ts
corrected by creating proper namespaceURI
=> fix: viewBox attribute not camelCase.

package.json, pnpm-lock.yaml, src/components/IconSet.vue, src/hooks/search.ts
This pull request improves the search experience that is center of Icones, by using the [fzf](https://fzf.netlify.app/docs/latest) library to provide fuzzy matching.
<table>
<tr>
<td><strong>Condition
<td><strong>Before
<td><strong>After
<tr>
<td>Search all icons & simple query
<td>🚀 <code>String#includes
<td>🚀 <code>String#includes
<tr>
<td>Search all icons & complex query
<td>❌ No result
<td>✅ fzf (extended match)
<tr>
<td>Search icon set & simple query
<td>🟡 fuse.js
<td>🟢 fzf (fast match)
<tr>
<td>Search icon set & complex query
<td>🟡 fuse.js
<td>🟢 fzf (extended match)
</table>
- Simple query: a string containing no space or any character (`'^$!`) used in extended match
- Complex query: not simple search :)
- Fast match: use [a faster fuzzy search …
=> feat: improve search experience using `fzf`

src/components/FAB.vue
=> fix: FAB round

src/components/ActionsMenu.vue, src/components/Bag.vue, src/utils/pack.ts
Add option to download json.
link https://github.com/unocss/unocss/discussions/1733.
=> feat(download): download json data

src/components/CollectionEntry.vue, src/components/Icons.vue, src/main.css
Added a few css perf tweaks which improves rendering by utilising GPU
=> perf: use GPU to render

src/components/IconSet.vue
=> fix: exclude `all` for npm link

src/components/IconSet.vue
=> chore: lint fix

src/components/IconDetail.vue, src/utils/icons.ts
Add vue ts components to facilitate direct copying and use in the ts environment.
=> feat: add vue ts component

src/components/HelpPage.vue
```diff
- ... is a band new solution to use generate icons on-demand as components.
+ ... is a brand new solution to generate icons on-demand as components.
```
This PR fixes the typo as shown in the diff above.
=> chore: fix typo

src/components/IconDetail.vue, src/utils/icons.ts
Add support for Qwik framework. It's like react, but JSX is HTML standard.
=> feat: add Qwik

src/main.ts, tsconfig.json
With current logic there is no auto page reload, should be done manually or next browsing.
=> feat: use pwa virtual module

src/components/IconDetail.vue, src/utils/icons.ts
Add solid support 
Thanks for this pr it was easy to replicate and add the support solid-js https://github.com/antfu/icones/pull/133
=> feat: add solid support

src/components.d.ts, src/components/Drawer.vue, src/components/IconSet.vue, src/components/Navbar.vue, src/components/SearchBar.vue, src/data/index.ts, src/pages/index.vue, src/store/localstorage.ts
Some searchfields was missing parts(close button or had a diffrent style)
I think it's easier to track them as one component
=> chore: refactor searchfields into one component

src/components/ColorPicker.vue
=> fix: remove `z-index` of `ColorPicker`

src/components/CollectionEntry.vue
when hover near to remove button, there is a add to fav button
[148](https://github.com/antfu/icones/issues/148)
=> fix: add favorite button to recent CollectionEntry

src/utils/icons.ts
=> fix: download svg currentColor

src/utils/case.ts
add a slash to `utils/case`.
I created a pull request without knowing if I should create an issue.
=> feat: add slash template

src/utils/case.ts
Refer: https://www.npmjs.com/package/@iconify/tailwind
Thanks.
=> feat: support double hypen template

src/main.css, src/pages/index.vue
Hi, antfu !! @antfu 
I am your fans !!
* I found the page will unfriendly shake when quickly hovering and not hovering.
* There is noticeable lag when inputting in the home page's input box.
Here is the problem
https://github.com/antfu/icones/assets/74909529/e505717d-0fc2-4782-ab41-c8be5d1ed17b
In the video, I try to delete the word in the search input, but it is not work. So I add  a debounce, it makes the page start to compute the filter array when typing stops some time.
I didn't find any obvious lag when typing in other search boxes, so I only modified this one. 
Thank you !!!!!
Please give me some advice !
=> fix: remove hiding scrollbar on hover and optimize input lag in the home page search box.

src/components/IconSet.vue
fixes: #84
https://github.com/antfu/icones/issues/84
=> fix: icon tooltips may be covered by the sidebar

src/pages/settings.vue
=> fix: scrolling on settings page, close #171

.github/renovate.json
This pull request updates the Renovate configuration in the renovate.json file to enhance the update strategy for the @iconify/json dependency. The aim is to ensure that important updates for the @iconify/json package are checked more frequently while maintaining the existing update schedule for other dependencies.
This configuration modification allows for more frequent update checks for the @iconify/json dependency, providing timely responsiveness to potential updates, bug fixes, and improvements. The stability period ensures a brief window for assessment before updates are applied. Meanwhile, the existing update schedule for other dependencies remains unaffected, maintaining a balance between staying current and ensuring stability.
=> ci: auto update @iconify/json daily

.github/renovate.json
This new configuration provides more granular control over update frequencies, resulting in improved maintenance and flexibility. Additionally, the new configuration has been validated by renovate-config-validator to ensure its correctness.
The new configuration leverages the recommended settings (config:recommended) for a more standardized and optimized approach.
Improved stability: The minimumReleaseAge setting has been introduced to ensure stability before automerging daily updates for the @iconify/json package.
The new configuration has undergone validation by renovate-config-validator, passing successfully to ensure its correctness and adherence to Renovate's guidelines.
None
=> ci: improve renovate.json

.github/renovate.json
This PR enhances the Renovate configuration for more effective dependency management, including refined update strategies and scheduling.
This pull request focuses on improving the Renovate configuration to optimize dependency management within the repository. The changes aim to enhance the update strategies, automerging behavior, and scheduling for different types of dependencies.
Changes Made:
Enhanced Package Rules: The updated configuration includes a more refined approach to handling updates for the @iconify/json package. It covers minor, patch, pin, and digest updates, ensuring a comprehensive update process.
Continued Exclusion Strategy: Exclusion patterns for packages other than @iconify/json have been maintained, allowing updates to be applied on a weekly basis as before.
None …
=> chore: improve renovate.json

src/components/Bag.vue, src/utils/pack.ts
add functionality to download icons on the bag as sprite
https://github.com/antfu/icones/assets/45778229/b0938cb2-987f-4741-a3f2-17bd5ce59397
#119
=> feat: download SVG Sprite

src/components/IconDetail.vue, src/utils/icons.ts
Adds [Astro](https://github.com/withastro/astro) support
N/A
N/A
=> feat: add astro support

src/components/IconDetail.vue
=> feat: Add license link to IconDetail

src/components/IconSet.vue
Makes the search query is synchronized with the input value
fix #296
=> fix: the search query is not synchronized with the input value

src/utils/case.ts
Add icon case for @iconify/tailwind.
Ref: https://iconify.design/docs/usage/css/tailwind/#html
=> feat: add icon case for @iconify/tailwind

src/components/IconSet.vue
Fix UI display issue for the collapsible drawer toggle button.
fixes #316
=> fix: adjusted btn z-index and hide on small screens

unocss.config.ts
Address the issue of button shrinking on the settings page.
Before:
After:
N/A
N/A
=> fix: icon button is shrinking on settings page

src/components/HelpPage.vue
https://github.com/user-attachments/assets/2135b852-afb2-4169-a3fb-f2c34a684294
=> fix(help-page): update @unocss/preset-icons url

src/components/Icon.vue
=> fix: layout issues on large screens
