antfu-collective/icones

src/components/Navbar.vue
I have accessed icones from Safari and seen the glitch of flex on top nav.
I have added flex value as class, `flex-1-0`, to nav.
Not sure that it would be the best practice, please give me an advice. 😁
-----
If you have any feedback or suggestion, do not hesitate to tell me.
=> [Fix] CSS Nav on Safari

package.json, src/App.vue, src/components/IconDetail.vue, src/data/index.ts, src/env.ts, src/main.ts
Hi @antfu 
As discussed, I've tried to make changes to the vue app so a single codebase could work for both vscode and browser environments.
I've also opened a PR at https://github.com/afzalsayed96/vscode-icones/pull/1 which introduces loading built assets locally.
**List of changes**
1. Replace `navigator.writeText` with `copy-text-to-clippboard` package
2. Styled default scrollbar in `App.vue` so it looks better inside vscode
3. Introduce a `basePath` and `staticPath` runtime env variable for vscode environment
=> chore: changes for vscode extension

src/main.postcss
One last fix before publishing changes to the extension. The `overscroll-behavior` property was preventing scrolling via mouse wheel inside vscode.
=> fix: remove overscroll-behavior

index.html, src/main.postcss
Two more tiny styling related changes
1. Add `body { padding: 0; }` rule to override vscode's added padding to the body
2. Add default body text color for light mode which also override vscode default color
=> fix: body padding and color

src/components/Bag.vue, src/utils/pack.ts
Previously we could only download zip packages of SVG files. 
This PR supports packaging of `vue`, `jsx`, `tsx` components.
=> feat: support pack component zip

src/components/IconDetail.vue, src/utils/icons.ts
This enables the ability to quickly copy icons to an SVG Symbol. 
https://developer.mozilla.org/en-US/docs/Web/SVG/Element/symbol
=> feat: copy icon to SVG Symbol, close #30

src/components/IconDetail.vue, src/store/localstorage.ts, src/utils/icons.ts
This add a **copy with color** checkbox that is by default unchecked to keep initial behavior.
When checked, it either use or reproduce the [color props from iconify api](https://github.com/iconify/json-tools.js/blob/master/src/svg.js#L332-L334), so it works with all export types
> url: `https://api.iconify.design/mdi-light:gift.svg?color=%23ff8000`
> css: `background: url('https://api.iconify.design/mdi-light:gift.svg?color=%23ff8000') no-repeat center center / contain;`
only the html export differ from others, using a style instead
> html: `<span class="iconify" data-icon="mdi-light:gift" data-inline="false" style="color: #ff8000"></span>`
close #52
=> feat: copy with color

src/components/ActionsMenu.vue
The select element on the nav is too wide causing it to float over the dark mode switch button.
=> fix: select on menu floats over other buttons

src/components/ActionsMenu.vue, src/components/IconDetail.vue, src/components/IconSet.vue, src/store/localstorage.ts
I found it useful to now support the ability to copy the name of the icon directly in the drawer after clicking the icon.  However, is it possible to support a mode switch? Clicking on the icon will directly copy the icon name.  Because as a developer, a lot of times I just need to find the icon I want and copy its name so I can reference it in my projects.
=> feat: add copying mode

src/utils/htmlToJsx.ts
Such as `EosIconsThreeDotsLoading` icon,  When I copied it as a vue component, its attributes like `attributeName` and `repeatCount` were converted to `attributename` and `repeatcount`. Therefore, causing the animation to fail.
=> fix: should not convert some attributes to lowercase

src/utils/htmlToJsx.ts, src/utils/icons.ts
There are some differences between react jsx and pure jsx. React jsx doesn't support namespace tags, so when copying it, the attribute `xmlns:xlink` should be transformed to `xmlnsXlink`. Also, `class` should be `className`.
=> fix: transform svg to react jsx correctly

src/components/IconSet.vue, src/pages/collection/[id].vue, src/pages/index.vue
This pull request adds shortcuts to search and close icon detail, for a faster workflow.
- On index page <kbd>/</kbd> goes to all icon search
- To comply with this change, the search box is now auto focused
- On icon search page <kbd>/</kbd> focuses the search box
- <kbd>Esc</kbd> closes icon detail when opened
There is also a slight tweak in how search box handles input, it now correctly responds inputs via a IME (so one doesn't need to submit the word in order to get search feedback).
https://user-images.githubusercontent.com/44045911/180647546-64de4fee-c76f-4e4d-9b12-dcdc8e4ed377.mov
=> feat: add shortcuts to search and close icon detail

src/components/Drawer.vue, src/components/IconSet.vue, src/components/WithNavbar.vue, src/data/index.ts, src/pages/index.vue, src/store/localstorage.ts, src/store/search.ts
This PR adds a way to search for specific categories, as well as order them alphabetically. These features are on the index page and on the drawer.
I find myself `Ctrl+F`ing for a specific icon set each time I open Icones. While looking if a PR or issue was open, I saw #88, and I thought it was relevant so I also implemented it.
Additionally, I also fixed a few edge cases where the search input wasn't focusing automatically.
Closes https://github.com/antfu/icones/issues/88
https://user-images.githubusercontent.com/16060559/187660576-627178cf-ca91-490a-8d51-ce4630b41bd5.mp4
=> feat: search and sort categories

package.json, pnpm-lock.yaml, src/components/IconDetail.vue, src/components/IconSet.vue
Switches to modern Clipboard API to copy code samples to clipboard. Fixes copy to clipboard not working in Safari.
https://github.com/antfu/icones/issues/98
Clipboard API works in all modern browsers, does not require third party dependencies.
=> fix: use Clipboard API to copy code samples

src/components/IconSet.vue
Fix `categroy` layout overflow
=> fix: categroy layout overflow

src/utils/icons.ts
Adds the `xmlns="http://www.w3.org/2000/svg"` attribute to locally generated SVGs, to have them properly rendered by some browsers, like firefox.
It also adds the `xmlns:xlink="http://www.w3.org/1999/xlink"` attribute if the SVG uses xlink in the body, like the iconify api does.
#103 
After calling [`iconToSVG` ](https://github.com/iconify/api/blob/e045c74d0968e8e62239f6475d5241505c2b0ebd/src/http/responses/svg.ts#L53) (which is the same thing as `buildIcon`) the iconify api calls [`iconToHTML`](https://github.com/iconify/iconify/blob/main/packages/utils/src/svg/html.ts), which also adds the two missing attributes.
=> fix: include xmlns attribute in SVGs

src/main.ts, src/sw.ts
I guess we can do 2 more optimizations on icones website with PWA:
- remove internal cache (if any): it seems we're caching visited collections in memory?
- remove split requests: when requesting a collection, there are a few requests, we can use just one
=> feat: open caches and add fallback on sw interception

src/main.ts, src/sw.ts
This PR includes some sw optimizations:
- map local iconify collections using sw precache manifest revision entry: current version will end with duplicates entries, for SW precache and for local request without the `?__WB_REVISION__=<revision>` entry
- adds some response header to avoid CORS errors: this can be only tested on production, maybe we can enable PR preview
I'll try to move all local collections outside precache on its own cache using runtime config, current version will take long time to install and activate the sw, it needs to download ~400MB, then it is activated: visit any collection without sw installed and activated will use iconify request api.
This PR will be on draft a few minutes, checking on my local runtime caching changes.
=> fix: handle cached collections urls properly

src/components/Bag.vue, src/utils/pack.ts
close #160 
#160 
This pr will change inner file name of zip file when the type of download is SVG or JSON
=> fix: use origin icon name to load icon data, close #160

src/utils/icons.ts
Exports pure svg output for svelte component with props support  instead of jsx
fixes #143 
Here are some examples of the issue with previous and fixed implementation:
[Svelte REPL example](https://svelte.dev/repl/b4349c6a987f41198c489a380deb51be?version=4.1.1) 
#143
=>  fix: export correct svelte component, close #143

.github/renovate.json
The current Renovate configuration encounters an issue when updating the "@iconify/json" package. Despite the availability of a release timestamp for "@iconify/json," Renovate does not utilize this timestamp by default.
By introducing the "matchDatasources" setting with the value ["npm"] in the renovate.json file, we instruct Renovate to utilize the NPM registry datasource. This enhancement empowers Renovate to access the release timestamp for "@iconify/json" in the NPM registry, allowing updates to be triggered promptly, even if the package is newer than one day old.
None
None
=> chore: tweak renovate.json for Enhanced @iconify/json Updates

src/data/variant-category.ts
Just changed `Duetone` to `Duotone` in phosphor icon variants 👍
=> fix: correct spelling for ph variants

.github/renovate.json
Modify the Renovate configuration to enable "automerge" for daily non-major updates of the @iconify/json package.
This pull request enhances the existing Renovate configuration to incorporate automerge functionality for daily non-major updates of the @iconify/json package.
=> ci: enable Automerge for @iconify/json in Renovate Configuration

src/utils/case.ts
Adds an additional format for UnoCSS users that prefer the colon over the dash. Ordered before the dash version to keep consistency with the non-i-prefixed formats above.
none
Similar to #158 and #161
=> feat: support unocss with colon format

electron/package.json
Fixed the build script where used `yarn copy` instead of the `pnpm copy`. The original script will cause conflicts with the `"packageManager": "pnpm@8.7.1"` wrote in the package.json.
=> chore: fix the build script

src/utils/htmlToJsx.ts
For example, if I copy the `line-md:uploading-loop` icon to a vue-ts component, attributes such as `stroke-dasharray` will be converted, causing related attributes to become invalid.
=> fix: do not convert attributes starting with stroke

scripts/prepare.ts
When the parent directory uses a Chinese path, it will report an error: 'no such file or directory'.
=> fix: chinese path error 'no such file or directory'

package.json, pnpm-lock.yaml
When installing dependencies on my Windows laptop `ttf2woff2` is built and it is failing (no idea if required):
<details>
<summary>error running pnpm install --frozen-lockfile</summary>
```shell
node_modules/.pnpm/ttf2woff2@3.0.0/node_modules/ttf2woff2: Running install script...
node:events:492
throw er; // Unhandled 'error' event
^
Error: ENOENT: no such file or directory, open 'D:\work\antfu\icones\D:\work\antfu\icones\node_modules\.pnpm\ttf2woff2@3.0.0\node_modules\ttf2woff2\builderror.lo
g'
Emitted 'error' event on WriteStream instance at:
at WriteStream.onerror (node:internal/streams/readable:1004:14)
at WriteStream.emit (node:events:514:28)
at emitErrorNT (node:internal/streams/destroy:151:8)
at emitErrorCloseNT (node:internal/streams/destroy:116:3)
at …
```
=> chore: exclude `ttf2woff2` build when installing dependencies

src/components/DarkSwitcher.vue, src/main.css
Used `startViewTransition` and `animate` API to add toggle theme color transition like nuxt devtools. 
I'm not quite sure about if the `isAppearanceTransition` var should be defind in `DarkSwitcher` component.
=> feat(theme): add transition like nuxt devtools

src/utils/icons.ts
Solid component does not work
There should not be `key` and the attributes should not be in camelCase, can test in https://playground.solidjs.com/
=> fix: convert to solid component

src/components/IconDetail.vue, src/utils/icons.ts
=> feat: add react native to the list of useable options

src/utils/htmlToJsx.ts
the `React.SVGAttributes.strokeLinecap` etc. requires camelCase attribute
=> fix: svg stroke attribute to camel-case at html to jsx

package.json, pnpm-lock.yaml, src/App.vue, src/components/Icons.vue, src/hooks/color.ts, src/hooks/index.ts, src/hooks/search.ts, src/main.css, src/main.ts
When the prompt is at the border, it is not fully displayed
=> fix: tip is not displayed completely on boundaries

src/pages/index.vue
Just noticed that deleting a collection from recent list does not trigger UI update, here's the quick fix.
=> fix: update homepage when favorite / recent collections change

src/utils/icons.ts
Concern: the result of `encodeSvgForCss()` intentionally escapes `"` (double quote) because it is then be used in generating the CSS `url("...")`. That is to say, the `'` (single quote) is not escaped.
There's a even more shorter algorithm which does not escace `<` and `"` `'` [in esbuild](https://github.com/evanw/esbuild/blob/main/internal/helpers/dataurl.go). The use case is to be assigned to `img.src` in JavaScript, like in React and Vue element props. I guess this is not a handy choice when I just want to copy and paste the url to CSS/HTML.
=> feat: return shorter data url if possible

src/components/IconDetail.vue
The `code.value` seems to be cached by `type`, so the popover value doesn't change when only the icon changes.
=> fix: code value cache on show

src/components/IconDetail.vue
View on
Before
After
Fix #344 
none
=> fix: unify button and link size in IconDetail

src/components/IconDetail.vue
This PR updates the URL used for linking to Iconify icon set pages `https://icon-sets.iconify.design/`.
The URL parameter `query` used for search icons (e.g., `https://icon-sets.iconify.design/mingcute/?query=crystal-ball-fill`) has been observed to be deprecated on the Iconify website.
Please check the picture below
_No search results are filtered._
The site now uses the `icon-filter` parameter for the same functionality (e.g., `https://icon-sets.iconify.design/mingcute/?icon-filter=crystal-ball-fill`).
This is a really great project, thank you!
The only minor issue I noticed was the outdated Iconify link, which prompted me to open this PR.
=> fix: iconify URL parameter from 'query' to 'icon-filter'

src/components/Bag.vue, src/utils/svg/helpers.ts, src/utils/worker/index.ts
Added missing frameworks to the Download Zip option in the Bag, using the same list in the IconDetail.vue component excluding PNG format.
Applied same logic for file extension used in download function in the web worker.
resolves #370
=> feat: allow download missing frameworks zip from bag
